USE toydb;

CREATE TABLE IF NOT EXISTS toys (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  name VARCHAR(255) NOT NULL,
  manufacturer VARCHAR(255),
  series VARCHAR(255),
  sub_series VARCHAR(255),
  toyline VARCHAR(255),
  `year` SMALLINT UNSIGNED,
  accessories TEXT,
  `condition` VARCHAR(50),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS toy_photos (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  toy_id INT UNSIGNED NOT NULL,
  filename VARCHAR(512) NOT NULL,
  original_name VARCHAR(512),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (toy_id) REFERENCES toys(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- If updating an existing database, try to add missing columns safely
ALTER TABLE toys ADD COLUMN IF NOT EXISTS toyline VARCHAR(255);
ALTER TABLE toys ADD COLUMN IF NOT EXISTS `year` SMALLINT UNSIGNED;
